### ISSUE TITLE
该模块是从rest_xops项目中抽出来的吧？

### ISSUE THREAD

**Issue by dyzsoft** [hyyc554/drf_rbac#2]
该模块是从rest_xops项目中抽出来的吧？
代码命名，注释基本都没改

**Comment by hyyc554** [comment]
> 该模块是从rest_xops项目中抽出来的吧？
> 代码命名，注释基本都没改

是的，目前已经在readme中指出了项目来源，这个主题代码确实是从rest_xops项目抽离出来的，我在这个基础上进行了一些热刺开发，比如通过自定义的JSONRenderer，实现了返回结果的统一，让整个模块更加容易的嵌入到已经存在其他项目中。

目前rest_xops已经不再维护了，最初是考虑我这边继续完善一下的，目前我这里的这个代码也还是有一些问题，但是最近工作变动，也没有时间在继续开发维护了。

如果您觉得这个代码仓库的存在不合适，我这边可以马上删除

**Comment by yance-dev** [comment]
> 该模块是从rest_xops项目中抽出来的吧？
> 代码命名，注释基本都没改

是的，目前已经在readme中指出了项目来源，这个主体代码确实是从rest_xops项目抽离出来的，我在这个基础上进行了一些二次开发，比如通过自定义的JSONRenderer，实现了返回结果的统一，让整个模块更加容易的嵌入到已经存在其他项目中。

目前rest_xops已经不再维护了，最初是考虑我这边继续完善一下的，目前我这里的这个代码也还是有一些问题，但是最近工作变动，也没有时间在继续开发维护了。

如果您觉得这个代码仓库的存在不合适，我这边可以马上删除
